#!/usr/bin/env bash

export normal=$'\e[0m' # normal
export bold=$(tput bold)

# Normal colours
export black=$(tput setaf 0) # black
export red=$(tput setaf 1) # red
export green=$(tput setaf 2) # green
export yellow=$(tput setaf 3) # yellow
export blue=$(tput setaf 4) # blue
export magenta=$(tput setaf 5) # magenta
export cyan=$(tput setaf 6) # cyan
export white=$(tput setaf 7) # white

# Bold colours
export bold_black="$bold$black" # bold black
export bold_red="$bold$red" # bold red
export bold_green="$bold$green" # bold green
export bold_yellow="$bold$yellow" # bold yellow
export bold_blue="$bold$blue" # bold blue
export bold_magenta="$bold$magenta" # bold magenta
export bold_cyan="$bold$cyan" # bold cyan
export bold_white="$bold$white" # bold white

function success() {
    echo "${bold_green}${1}${normal}"
}

function error() {
    echo "${bold_red}${1}${normal}"
}

function chkroot() {
    if [[ $EUID -ne 0 ]]; then
        error "Shade must be run as a root user"
        exit 1
    fi
}

function help() {
    cat <<EOF
Usage: shade [OPTION] [...]

Options:
    -h, --help    Show this text
EOF
    
}

function setup() {
    chkroot
    success "Beginning setup"
    mkdir /usr/local/shade/ > /dev/null 2>&1
    mkdir /usr/local/shade/log/ > /dev/null 2>&1
    mkdir /usr/local/shade/cache/ > /dev/null 2>&1
    git clone https://github.com/shade-linux/buildscripts/ /usr/local/shade/main/
    success "Setup done!"
}


function install() {
    chkroot
    for pack in ${@:2:9999}; do
        read -r -p "${bold_green}Open ${pack} buildscript? [Y/n] ${normal}" response
        response=${response,,}
        if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
            if command -v bat &> /dev/null
            then
                bat -l sh --decorations never /usr/local/shade/main/packages/${pack}/package 2>/dev/null || error "${2} buildscript not found!"
            else
                less /usr/local/shade/packagmain/es/${pack}/package || error "${2} buildscript not found!"
            fi
        fi
        find /usr/local/shade/ -name "*" > /usr/local/shade/main/packages/${pack}/pre-install
        success "Installing ${pack}"
        rm /usr/local/shade/cache/${pack}
        if ! bash /usr/local/shade/main/packages/${pack}/package; then
            error "${pack} failed to install!"
        else
            find /usr/local/shade -name "*" > /usr/local/shade/main/packages/${pack}/post-install
            echo > /usr/local/shade/main/packages/${pack}/installed
            success "${pack} installed!"
        fi
    done
}

function remove() {
    chkroot
    for pack in ${@:2:9999}; do
        read -r -p "${bold_green}Uninstall ${pack}? [Y/n] ${normal}" response
        response=${response,,}
        if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
            diff /usr/local/shade/main/packages/${pack}/pre-install /usr/local/shade/main/packages/${pack}/post-install | tail -n +2 | cut -c 3- | xargs rm -rf
            rm /usr/local/shade/main/packages/${pack}/installed
            success "${pack} uninstalled!"
        fi
    done
}

function query() {
    cat /usr/local/shade/main/packages/*/*${2,,}*/meta 2>/dev/null || error "${2} not found!"
}

function update() {
    chkroot
    success "Beginning update..."
    cd /usr/local/shade/main/
    if ! git pull; then
        error "Update failed!"
    else
        success "Update completed!"
    fi
}

function upgrade() {
    chkroot
    for i in $(find /usr/local/shade/main/packages -iname 'installed' -exec dirname {} \; | sed -e 's/\/.*\///g'); do
        cd /usr/local/shade/main/${i}
        if ! git pull | grep -q 'Already up to date'; then
            cd ..
            rm -rf ${i}
            bash /usr/local/shade/main/packages/${i}/package
        fi
    done
}

case "$1" in

    -h) help ;;
    --help) help ;;
    
    -s) setup ;;
    --setup) setup ;;

    -i) install $@ ;;
    --install) install $@ ;;

    -r) remove $@ ;;
    --remove) remove $@ ;;

    -q) query $@ ;;
    --query) query $@ ;;

    -u) update ;;
    --update) update ;;

    -U) upgrade ;;
    --upgrade) upgrade ;;

esac
