name: Bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install bash
        run: |
          sudo ./src/shade setup
          sudo cp ./src/config /etc/shade/
          yes | sudo ./src/shade install bash
