- name: Shell Linter
  # You may pin to the exact commit or the version.
  # uses: azohra/shell-linter@ad879393449ead286ce03accee8475a4cec1358d
  uses: azohra/shell-linter@v0.5.0
  with:
    # Execute lint check on a specific file or folder.
    path: src/shade
    # Specify minimum severity of errors to consider.
    severity: # optional, default is style
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
